### PR TITLE
from neural_pipeline.train_config import TrainConfig for line 104

### PR DESCRIPTION
**Pull request by cclauss**
[flake8](http://flake8.pycqa.org) testing of https://github.com/toodef/neural-pipeline on Python 3.7.1

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./neural_pipeline/data_processor/data_processor.py:103:53: F821 undefined name 'TrainConfig'
    def __init__(self, model: Module, train_config: 'TrainConfig', device: torch.device = None):
                                                    ^
./neural_pipeline/data_processor/data_processor.py:136:75: F821 undefined name 'AbstractMetricsProcessor'
    def process_batch(self, batch: {}, is_train: bool, metrics_processor: 'AbstractMetricsProcessor' = None) -> np.ndarray:
                                                                          ^
2     F821 undefined name 'TrainConfig'
2
```
__E901,E999,F821,F822,F823__ are the "_showstopper_" [flake8](http://flake8.pycqa.org) issues that can halt the runtime with a SyntaxError, NameError, etc. These 5 are different from most other flake8 issues which are merely "style violations" -- useful for readability but they do not effect runtime safety.
* F821: undefined name `name`
* F822: undefined name `name` in `__all__`
* F823: local variable name referenced before assignment
* E901: SyntaxError or IndentationError
* E999: SyntaxError -- failed to compile a file into an Abstract Syntax Tree

### CODE REVIEW

**Comment by toodef** [comment]
Hi @cclauss! Thanks for your PR!
I'm using type definition in like `train_config: 'TrainConfig'` cause `import TrainConfig` make the import loop and throw `ImportException`.
I think this is an error in architecture, but i don't know how to fix it(
Maybe U have any ideas? How much worse to use `train_config: 'TrainConfig'`?

**Comment by cclauss** [comment]
I do not know typing very well.  Perhaps check out the few past release of __flake8__ as these checks for types were recently added and there is probably so discussion on pros & cons.

**Comment by toodef** [comment]
Ok. I will hold this PR before I deal with it.
Thanks!

**Comment by toodef** [comment]
Can't find a solution for python loop importing. PR closed.

**Pull request closed without merging**
